INSERT INTO COURSE 
    (COURSE_ID, USER_NAME, TITLE, DESCRIPTION, START_DATE, END_DATE, RESEARCH_AUTHORIZATION, CREATED)
VALUES 
    ($1, $2, $3, $4, $5, $6, $7, $8)
    /*($1, $2, $3, $4, $5, $6, CURRENT_TIMESTAMP)*/
RETURNING *;
