SELECT * FROM ASSIGNMENT 
  JOIN QUESTION ON 
    QUESTION.ASSIGNMENT_ID = ASSIGNMENT.ID
  JOIN ANSWER ON 
    ANSWER.ASSIGNMENT_ID = ASSIGNMENT.ID AND ANSWER.user_name = $2 
  WHERE ASSIGNMENT.COURSE_ID = $1;
