UPDATE COURSE SET
    COURSE_ID = $2,
    USER_NAME = $3,
    TITLE = $4,
    DESCRIPTION = $5,
    START_DATE = $6,
    END_DATE = $7,
    RESEARCH_AUTHORIZATION = $8,
    CREATED = $9
WHERE ID = $1 RETURNING *;
