INSERT INTO feedback (USER_NAME, COURSE_ID, CREATED, VALUE, ORDER_NBR, ASSIGNMENT_ID)
VALUES($1, $2, $3, $4, $5, $6)
    ON CONFLICT (id) DO UPDATE SET
    USER_NAME = $1, COURSE_ID = $2, CREATED = $3, VALUE = $4, ORDER_NBR = $5, ASSIGNMENT_ID = $6
                            RETURNING *
