INSERT INTO feedback (USER_NAME, COURSE_ID, CREATED, FEEDBACK_VALUE, ORDER_NBR, ASSIGNMENT_ID, STUDENT)
VALUES($1, $2, $3, $4, $5, $6, $7)
    ON CONFLICT (id) DO UPDATE SET
    USER_NAME = $1, COURSE_ID = $2, CREATED = $3, FEEDBACK_VALUE = $4, ORDER_NBR = $5, ASSIGNMENT_ID = $6, STUDENT = $7
                            RETURNING *
