
INSERT INTO feedback (ID, USER_NAME, COURSE_ID, CREATED, FEEDBACK_VALUE, ORDER_NBR, ASSIGNMENT_ID)
VALUES($1, $2, $3, $4, $5, $6, $7)
    ON CONFLICT (id) DO UPDATE SET
    ID = $1, USER_NAME = $2, COURSE_ID = $3, CREATED = $4, FEEDBACK_VALUE = $5, ORDER_NBR = $6, ASSIGNMENT_ID = $7
                            RETURNING *
