CREATE TABLE IF NOT EXISTS answers(
    ID integer UNIQUE NOT NULL,
    STUDENTID VARCHAR(50),
    TIMESTAMP TIMESTAMP,
    TOPIC_ANSWER VARCHAR(255),
    DESCRIPTION_ANSWER VARCHAR(255),
    MULTIPLE_CHOICE_ANSWER int,
    PRIMARY KEY(id)
    );