
INSERT INTO answer (ID, USER_NAME, COURSE_ID, CREATED, VALUE, ORDER_NBR, ASSIGNMENT_ID, EDITED)
  VALUES($1, $2, $3, $4, $5, $6, $7, $8)
  ON CONFLICT (id) DO UPDATE SET
  ID = $1, USER_NAME = $2, COURSE_ID = $3, CREATED = $4, VALUE = $5, ORDER_NBR = $6, ASSIGNMENT_ID = $7, EDITED = $8
RETURNING *

